# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dartboard}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Taylor"]
  s.date = %q{2011-04-06}
  s.description = %q{Randomly select values based on percentages}
  s.email = %q{scott@railsnewbie.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    "GPL_LICENSE",
    "Gemfile",
    "Gemfile.lock",
    "MIT_LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "dartboard.gemspec",
    "lib/dartboard.rb",
    "rake_tasks/flog.rb",
    "rake_tasks/gem.rb",
    "rake_tasks/rdoc.rb",
    "rake_tasks/rspec.rb",
    "rake_tasks/sloc.rb",
    "rake_tasks/tags.rb",
    "spec/dartboard/throwing_spec.rb",
    "spec/dartboard/version_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/smtlaissezfaire/dartboard}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Randomly select values based on percentages}
  s.test_files = [
    "spec/dartboard/throwing_spec.rb",
    "spec/dartboard/version_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<autotest>, [">= 4.4.6"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<autotest>, [">= 4.4.6"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

